# Generated by Django 3.1.5 on 2021-04-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=3000)),
                ('meaning', models.CharField(max_length=3000)),
                ('example', models.CharField(max_length=3000)),
                ('mnemonic', models.CharField(max_length=3000)),
            ],
        ),
    ]
