# Generated by Django 3.1.5 on 2021-04-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='choice1',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='choice2',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
