# Generated by Django 3.1.5 on 2021-04-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210422_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='choice2',
        ),
    ]
