# Generated by Django 3.1.5 on 2021-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210426_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='example',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='meaning',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='mnemonic',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
